/**
 * YouTube Data API v3 Client
 *
 * Provides typed access to YouTube's channel, video, and caption endpoints.
 * Requires YOUTUBE_API_KEY environment variable.
 */

const YOUTUBE_API_BASE = "https://www.googleapis.com/youtube/v3";

function getApiKey(): string {
  const key = process.env.YOUTUBE_API_KEY;
  if (!key) throw new Error("Missing YOUTUBE_API_KEY environment variable");
  return key;
}

// ── Types ────────────────────────────────────────────────────────────────────

export interface YouTubeChannel {
  id: string;
  title: string;
  handle: string;
  description: string;
  subscriberCount: number;
  videoCount: number;
  viewCount: number;
  thumbnailUrl: string;
  bannerUrl: string;
}

export interface YouTubeVideo {
  id: string;
  channelId: string;
  title: string;
  description: string;
  publishedAt: string;
  thumbnailUrl: string;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  durationSeconds: number;
  tags: string[];
}

export interface YouTubeCaption {
  id: string;
  language: string;
  name: string;
  isAutoGenerated: boolean;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

async function ytFetch<T>(endpoint: string, params: Record<string, string>): Promise<T> {
  const url = new URL(`${YOUTUBE_API_BASE}/${endpoint}`);
  url.searchParams.set("key", getApiKey());
  for (const [k, v] of Object.entries(params)) {
    url.searchParams.set(k, v);
  }

  const res = await fetch(url.toString(), { next: { revalidate: 300 } });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`YouTube API error (${res.status}): ${text}`);
  }

  return res.json() as Promise<T>;
}

function parseDuration(iso: string): number {
  // PT1H2M3S → seconds
  const match = iso.match(/PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?/);
  if (!match) return 0;
  const h = parseInt(match[1] || "0", 10);
  const m = parseInt(match[2] || "0", 10);
  const s = parseInt(match[3] || "0", 10);
  return h * 3600 + m * 60 + s;
}

// ── Channel lookups ──────────────────────────────────────────────────────────

/**
 * Resolve a YouTube channel URL to a channel ID + metadata.
 * Supports: @handle, /channel/UC..., /c/customname, /@handle
 */
export async function getChannelByUrl(url: string): Promise<YouTubeChannel | null> {
  // Extract handle or channel ID from URL
  const cleaned = url.trim().replace(/\/+$/, "");

  // @handle format
  const handleMatch = cleaned.match(/@([\w.-]+)/);
  if (handleMatch) {
    return getChannelByHandle(handleMatch[1]);
  }

  // /channel/UC... format
  const channelIdMatch = cleaned.match(/\/channel\/(UC[\w-]+)/);
  if (channelIdMatch) {
    return getChannelById(channelIdMatch[1]);
  }

  // /c/customname or just a handle without @
  const customMatch = cleaned.match(/\/c\/([\w.-]+)/);
  if (customMatch) {
    return getChannelByHandle(customMatch[1]);
  }

  // Try as raw handle
  if (/^[\w.-]+$/.test(cleaned)) {
    return getChannelByHandle(cleaned);
  }

  return null;
}

export async function getChannelByHandle(handle: string): Promise<YouTubeChannel | null> {
  const cleanHandle = handle.replace(/^@/, "");

  // Try forHandle parameter first (official way)
  const data = await ytFetch<{ items?: any[] }>("channels", {
    part: "snippet,statistics,brandingSettings",
    forHandle: cleanHandle,
  });

  if (!data.items?.length) {
    // Fallback: search for the channel
    const searchData = await ytFetch<{ items?: any[] }>("search", {
      part: "snippet",
      q: cleanHandle,
      type: "channel",
      maxResults: "1",
    });

    if (!searchData.items?.length) return null;

    const channelId = searchData.items[0].snippet.channelId;
    return getChannelById(channelId);
  }

  return parseChannel(data.items[0]);
}

export async function getChannelById(channelId: string): Promise<YouTubeChannel | null> {
  const data = await ytFetch<{ items?: any[] }>("channels", {
    part: "snippet,statistics,brandingSettings",
    id: channelId,
  });

  if (!data.items?.length) return null;
  return parseChannel(data.items[0]);
}

function parseChannel(item: any): YouTubeChannel {
  const snippet = item.snippet || {};
  const stats = item.statistics || {};
  const branding = item.brandingSettings || {};

  return {
    id: item.id,
    title: snippet.title || "",
    handle: snippet.customUrl || "",
    description: snippet.description || "",
    subscriberCount: parseInt(stats.subscriberCount || "0", 10),
    videoCount: parseInt(stats.videoCount || "0", 10),
    viewCount: parseInt(stats.viewCount || "0", 10),
    thumbnailUrl: snippet.thumbnails?.high?.url || snippet.thumbnails?.default?.url || "",
    bannerUrl: branding.image?.bannerExternalUrl || "",
  };
}

// ── Video lookups ────────────────────────────────────────────────────────────

/**
 * Get latest videos for a channel with full statistics.
 * Uses search.list (costs 100 units) + videos.list (costs 1 unit per 50 IDs).
 */
export async function getChannelVideos(
  channelId: string,
  maxResults = 50,
  publishedAfter?: string
): Promise<YouTubeVideo[]> {
  const params: Record<string, string> = {
    part: "snippet",
    channelId,
    type: "video",
    order: "date",
    maxResults: String(Math.min(maxResults, 50)),
  };

  if (publishedAfter) {
    params.publishedAfter = publishedAfter;
  }

  const searchData = await ytFetch<{ items?: any[] }>("search", params);
  if (!searchData.items?.length) return [];

  const videoIds = searchData.items
    .map((item: any) => item.id?.videoId)
    .filter(Boolean);

  if (!videoIds.length) return [];

  return getVideoDetails(videoIds);
}

/**
 * Get full video details for a batch of video IDs.
 * Batches up to 50 IDs per request.
 */
export async function getVideoDetails(videoIds: string[]): Promise<YouTubeVideo[]> {
  const results: YouTubeVideo[] = [];

  // Process in batches of 50
  for (let i = 0; i < videoIds.length; i += 50) {
    const batch = videoIds.slice(i, i + 50);
    const data = await ytFetch<{ items?: any[] }>("videos", {
      part: "snippet,statistics,contentDetails",
      id: batch.join(","),
    });

    if (data.items) {
      for (const item of data.items) {
        results.push(parseVideo(item));
      }
    }
  }

  return results;
}

function parseVideo(item: any): YouTubeVideo {
  const snippet = item.snippet || {};
  const stats = item.statistics || {};
  const content = item.contentDetails || {};

  return {
    id: item.id,
    channelId: snippet.channelId || "",
    title: snippet.title || "",
    description: snippet.description || "",
    publishedAt: snippet.publishedAt || "",
    thumbnailUrl:
      snippet.thumbnails?.maxres?.url ||
      snippet.thumbnails?.high?.url ||
      snippet.thumbnails?.default?.url ||
      "",
    viewCount: parseInt(stats.viewCount || "0", 10),
    likeCount: parseInt(stats.likeCount || "0", 10),
    commentCount: parseInt(stats.commentCount || "0", 10),
    durationSeconds: parseDuration(content.duration || ""),
    tags: snippet.tags || [],
  };
}

// ── Captions ─────────────────────────────────────────────────────────────────

/**
 * List available captions for a video.
 */
export async function getVideoCaptions(videoId: string): Promise<YouTubeCaption[]> {
  const data = await ytFetch<{ items?: any[] }>("captions", {
    part: "snippet",
    videoId,
  });

  if (!data.items?.length) return [];

  return data.items.map((item: any) => ({
    id: item.id,
    language: item.snippet?.language || "en",
    name: item.snippet?.name || "",
    isAutoGenerated: item.snippet?.trackKind === "ASR",
  }));
}

/**
 * Fetch transcript text for a video using the unofficial timedtext endpoint.
 * This doesn't require OAuth and works for auto-generated captions.
 */
export async function fetchTranscriptText(videoId: string): Promise<string | null> {
  try {
    // Use the unofficial YouTube transcript endpoint
    const url = `https://www.youtube.com/watch?v=${videoId}`;
    const pageRes = await fetch(url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
      },
    });

    if (!pageRes.ok) return null;

    const html = await pageRes.text();

    // Extract captions URL from the page
    const captionsMatch = html.match(/"captions":\s*(\{[^}]+\})/);
    if (!captionsMatch) return null;

    // Try to find timedtext URL
    const timedTextMatch = html.match(
      /https:\/\/www\.youtube\.com\/api\/timedtext[^"]+/
    );
    if (!timedTextMatch) return null;

    const timedTextUrl = timedTextMatch[0]
      .replace(/\\u0026/g, "&")
      .replace(/&fmt=json3/, "&fmt=srv3");

    const captionRes = await fetch(timedTextUrl);
    if (!captionRes.ok) return null;

    const captionXml = await captionRes.text();

    // Parse XML transcript — extract text from <text> elements
    const textMatches = captionXml.matchAll(/<text[^>]*>(.*?)<\/text>/gs);
    const lines: string[] = [];
    for (const match of textMatches) {
      const text = match[1]
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/<[^>]+>/g, "")
        .trim();
      if (text) lines.push(text);
    }

    return lines.length > 0 ? lines.join(" ") : null;
  } catch {
    return null;
  }
}
